# Speaker extraction model parameters
model: ECAPA_TDNN
log_input: True
trainfunc: softmaxproto
nPerSpeaker: 1
C: 1024
encoder_type: ECA


nOut: 256
n_mels: 80

pretrained_backbone_model : ./pretrained/official_ecapatdnn.model

train_list : ./datasets/manifests/libritts+light_1000h_v2.txt
train_path : ./datasets/libritts+light_1000h
test_path  : ./datasets/voxceleb1_ext

# Diffusion network parameters
train_diffusion : True
diffusion_network  : rdm_mlp
diffusion_pipeline : ddpm
diffusion_num_layers : 3

# Diffusion parameters
lr : 5e-4
lr_decay : 1
lr_decay_interval : 1
optimizer : adamW


conditional_diffusion : False
predict_type : sample
self_cond    : True
# training_clamp_norm : False
# sampling_clamp_norm : False
# sampling_final_norm : False
normalize_type : l2
use_speaker_label : False
